export default function LegalDisclaimer() {
  return (
    <div className="w-full border-t border-[var(--color-gunmetal)] mt-10 pt-6 pb-8 px-2">
      <p className="text-center text-xs text-[var(--color-steel)] leading-relaxed max-w-2xl mx-auto">
        <span className="text-[var(--color-silver)] font-medium">Not financial advice.</span>
        {' '}QuantumFolio is an educational and research tool. Portfolio allocations, metrics, and
        any output generated by this application are for informational purposes only and do not
        constitute financial, investment, legal, or tax advice. Past performance is not indicative
        of future results. Always consult a qualified financial adviser before making any investment
        decisions. The creators of QuantumFolio accept no liability whatsoever for financial
        decisions made based on this tool's output.
      </p>
    </div>
  );
}
